author_name: Daniel Thorpe
author_url: http://danthorpe.me
module_name: Operations
module_version: 2.3.0
github_url: https://github.com/danthorpe/Operations
readme: README.md
podspec: Operations.podspec

swift_version: 2.1
xcodebuild-arguments: -scheme,Operations-iOS

custom_categories:
  - name: Foundations
    children:
    - Operation
    - OperationQueue
    - OperationCondition
    - OperationObserver
    - LogSeverity
    - LoggerBlockType
    - LoggerType
    - Queue

  - name: Building Blocks
    children:
    - GroupOperation
    - BlockOperation
    - AlertOperation
    - ComposedOperation
    - DelayOperation
    - GatedOperation
    - UIOperation
    - MutuallyExclusive
    - NegatedCondition
    - SilentCondition
    - NoFailedDependenciesCondition
    - BlockCondition
    - BlockObserver
    - BackgroundObserver
    - NetworkObserver
    - TimeoutObserver
    - AlertPresentation

  - name: Featured
    children:
    - ReachableOperation
    - CloudKitOperation
    - UserLocationOperation
    - ReverseGeocodeOperation
    - ReverseGeocodeUserLocationOperation
    - NetworkOperation
    - WebpageOperation
    - ReachabilityCondition
    - UserNotificationCondition
    - RemoteNotificationCondition
    - URLSessionTaskOperation
    - UserConfirmationCondition

  - name: Device Capabilities
    children:
    - CapabilityType
    - AuthorizationStatusType
    - CapabilityRegistrarType
    - Capability
    - GetAuthorizationStatus
    - Authorize
    - CapabilityError
    - AuthorizedFor

  - name: Capability.Calendar
    children:
    - Calendar
    - EventsCapabilityRegistrarType
    - EKEventStore
    - EKAuthorizationStatus
    - _EventsCapability

  - name: Capability.Cloud
    children:
    - Cloud		
    - CloudContainerRegistrarType
    - CloudStatus
    - CloudCapability
    - CloudContainerRegistrar
    - _CloudCapability

  - name: Capability.Health
    children:
    - Health
    - HealthCapabilityStatus
    - HealthRequirement
    - HealthCapabilityRegistrarType
    - _HealthCapability

  - name: Capability.Location
    children:
    - Location
    - LocationUsage
    - _LocationCapability
    - LocationCapabilityRegistrarType

  - name: Capability.Passbook
    children:
    - _PassbookCapability
    - PassbookCapabilityRegistrarType

  - name: Capability.Photos
    children:
    - _PhotosCapability
    - PhotosCapabilityRegistrarType

  - name: Address Book
    children:
    - AddressBook
    - AddressBookAddPersonToGroup
    - AddressBookCreateGroup
    - AddressBookDisplayNewPersonViewController
    - AddressBookDisplayPersonViewController
    - AddressBookGetGroup
    - AddressBookGetResource
    - AddressBookGroup
    - AddressBookMapPeople
    - AddressBookOperation
    - AddressBookPerson
    - AddressBookRecord
    - AddressBookRemoveGroup
    - AddressBookRemovePersonFromGroup
    - AddressBookSource

