name: ProcedureKit CI

on: push

jobs:
  test:
    name: Test
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1    
      - name: Run a one-line script
        run: echo Hello, world!
